### PR TITLE
Lighten the json message

### PR DESCRIPTION
**Pull request by nicolas-b12**
This PR lightens the response from loadMessages and preserves essentials informations for the sake of parsing.

### CODE REVIEW

**Comment by aduchate** [comment]
Sure you don't wanna keep the zoneDescription ?

**Comment by nicolas-b12** [comment]
I think we don't need informations about the position and so, but if you see any use case for the zoneDescription, we can discuss it.

**Comment by nicolas-b12** [comment]
Maybe we could keep the "type" information but we can still embed it directly inside the zone

**Comment by nicolas-b12** [comment]
@aduchate it's ok according to @maxime2018

**Pull request merged**
